### ISSUE TITLE
RoboDialogFragment doesn't work - onViewCreated never fired

### ISSUE THREAD

**Issue by mattwhetton** [roboguice/roboguice#19]
Hi,

It looks to me like the RoboDialogFragment cant work as the injection appears to happen onViewCreated, but this never fires in a DialogFragment (as far as I can see)

**Comment by flossokay** [comment]
why was this issue closed?  I'm actually running into the same thing here.  It would be nice if roboguice took care of injection when calling onCreateDialog

**Comment by stephanenicolas** [comment]
RG 4 is no longer gonna include robo*classes, devs will have to create base
classes in their project.

We don't want to duplicate all code for all possible base classes.

Le lun. 29 févr. 2016 11:16, Martin Chiu <notifications@github.com> a
écrit :

**Comment by flossokay** [comment]
Is there an expected release date for roboguice4?

**Comment by stephanenicolas** [comment]
Yeah, very soon now. We are testing internally, all quality tests are
passed, we need more benchmarks, and some docs and then we will release.

Sorry, it took a long while to release RG4. We have tried all we code to
gain speed.

S.

2016-02-29 11:34 GMT-05:00 Martin Chiu <notifications@github.com>:
