### ISSUE TITLE
How to get " getSupportActionbar() "use  support-v7

### ISSUE THREAD

**Issue by hai046** [roboguice/roboguice#240]
I want to   use " getSupportActionbar()  " in  android-support-v7 please extend  v7.ActionbarActivity

**Comment by grantonzhuang** [comment]
```java
class YourActivity extends  RoboActionBarActivity
```
[Here is reference](http://roboguice.github.io/roboguice/site/3.0-alpha-3-SNAPSHOT/roboguice/apidocs/roboguice/activity/RoboActionBarActivity.html)
