### ISSUE TITLE
RoboGuice + proguard, com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchFieldError: UNKNOWN

### ISSUE THREAD

**Issue by dryganets** [roboguice/roboguice#245]
E/AndroidRuntime(31558): FATAL EXCEPTION: main
E/AndroidRuntime(31558): com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchFieldError: UNKNOWN
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
E/AndroidRuntime(31558):  at com.google.inject.internal.FailableCache.get(FailableCache.java:48)
E/AndroidRuntime(31558):  at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:68)
E/AndroidRuntime(31558):  at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:982)
E/AndroidRuntime(31558):  at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:989)
E/AndroidRuntime(31558):  at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:975)
E/AndroidRuntime(31558):  at roboguice.inject.ContextScopedRoboInjector.injectMembersWithoutViews(ContextScopedRoboInjector.java:235)
E/AndroidRuntime(31558):  at com.skype.android.app.SkypeActivity.onCreate(SkypeActivity.java:99)
E/AndroidRuntime(31558):  at com.skype.android.app.signin.LandingPageActivity.onCreate(LandingPageActivity.java:47)
E/AndroidRuntime(31558):  at android.app.Activity.performCreate(Activity.java:4465)
E/AndroidRuntime(31558):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1052)
E/AndroidRuntime(31558):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1932)
E/AndroidRuntime(31558):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1993)
E/AndroidRuntime(31558):  at android.app.ActivityThread.access$600(ActivityThread.java:127)
E/AndroidRuntime(31558):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1159)
E/AndroidRuntime(31558):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31558):  at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(31558):  at android.app.ActivityThread.main(ActivityThread.java:4507)
E/AndroidRuntime(31558):  at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(31558):  at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(31558):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
E/AndroidRuntime(31558):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
E/AndroidRuntime(31558):  at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(31558): Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchFieldError: UNKNOWN
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
E/AndroidRuntime(31558):  at com.google.inject.internal.Annotations$AnnotationChecker.hasAnnotations(Annotations.java:237)
E/AndroidRuntime(31558):  at com.google.inject.internal.Annotations.isBindingAnnotation(Annotations.java:301)
E/AndroidRuntime(31558):  at com.google.inject.internal.Annotations.findBindingAnnotation(Annotations.java:282)
E/AndroidRuntime(31558):  at com.google.inject.internal.Annotations.getKey(Annotations.java:268)
E/AndroidRuntime(31558):  at com.google.inject.spi.InjectionPoint.<init>(InjectionPoint.java:100)
E/AndroidRuntime(31558):  at com.google.inject.spi.InjectionPoint$InjectableField.toInjectionPoint(InjectionPoint.java:454)
E/AndroidRuntime(31558):  at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:699)
E/AndroidRuntime(31558):  at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:370)
E/AndroidRuntime(31558):  at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:93)
E/AndroidRuntime(31558):  at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:37)
E/AndroidRuntime(31558):  at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45)
E/AndroidRuntime(31558):  at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
E/AndroidRuntime(31558):  at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37)
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
E/AndroidRuntime(31558):  at com.google.common.cache.LocalCache$Segme
E/android.os.Debug( 1977): !@Dumpstate > dumpstate -k -t -n -z -d -o /data/log/dumpstate_app_error

**Comment by ashraful29** [comment]
I have similar problem

**Comment by stephanenicolas** [comment]
Roboguice is deprecated. For a list of alternatives, please visit 
https://github.com/stephanenicolas/toothpick#alternative-dependency-injection-di-engines-for-android
