### ISSUE TITLE
Which dependicies do I have to declare to use assistedinject and multibindings?

### ISSUE THREAD

**Issue by martinbrylski** [roboguice/roboguice#281]
I want to use roboguice using this dependency declaration in build.gradle:

```
dependencies {
    compile 'org.roboguice:roboguice:3.+'
}
```

I additionally want to use assistedinject and multibindigs. What do I need to add?

**Comment by stephanenicolas** [comment]
duplicate of https://github.com/roboguice/roboguice/issues/275
