### ISSUE TITLE
NullPointerException when Trying to make a Toast in injected Application

### ISSUE THREAD

**Issue by nicolasjafelle** [roboguice/roboguice#283]
If I inject MyApplication into an Activity and try to make a toast... it throws NullPointerException

```bash
java.lang.NullPointerException
at android.content.ContextWrapper.getApplicationContext(ContextWrapper.java:109)
at com.androidauthority.AndroidAuthorityApplication.sayHello(MyApplication.java:30)
at com.androidauthority.ui.activity.HomeActivity.onOptionsItemSelected(HomeActivity.java:44)
at android.app.Activity.onMenuItemSelected(Activity.java:2566)
```

My Module provider:

```java
public class ApplicationModuleProvider extends AbstractModule {

    private final MyApplication application;

    @Inject
    public ApplicationModuleProvider(final MyApplication application) {
        super();
        this.application = application;
    }

    @Override
    protected void configure() {
        bind(MyApplication.class).toInstance(application);
    }
}
```
and MyApplication class:

```java
public class MyApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        RoboGuice.overrideApplicationInjector(this, Modules.override(RoboGuice.newDefaultRoboModule(this)).with(new ApplicationModuleProvider(this)));

    }

    public void sayHello() {
        Toast.makeText(getApplicationContext(), "Hello Android", Toast.LENGTH_SHORT).show();
    }
}
```

**Comment by stephanenicolas** [comment]
There are different issues in your sample : 

* you should use the AndroidManifest's mechanism to declare your module. Refer to the instructions here : https://github.com/roboguice/roboguice/wiki/Your-First-Custom-Binding
* no need of the @Inject annotation for the constructor of a module, it is not created by injections.
* in your application, your say hello world doesn't make much sense : you could use `this` as first parameter. Why do you want to call `getApplicationContext()` here, the stack trace is not related with an injetion problem, the call simply fails.
* in your sample, there is no case for injection. It's not used.
* I believe that the binding of an application class to a custom class already works out of the box.
