### ISSUE TITLE
Incorrect wiki entry for provided injections

### ISSUE THREAD

**Issue by AlexKolpa** [roboguice/roboguice#287]
[This wiki page](https://github.com/roboguice/roboguice/wiki/Provided-Injections) mentions that the name of the name of the `SharedPreferences` object that is provided by default is "default". This however seems to be no longer the case.

I'm not sure the page is even up-to-date at all since the only revision is from 2012, but it does come up when searching on Google for "Roboguice provided injections".

**Comment by stephanenicolas** [comment]
The wiki is supposed be up to date. Can you give more details about the default file name you observe for shared preferences, to our knowledge, it is named default.

**Comment by AlexKolpa** [comment]
Sorry for not being clear enough in the issue, I didn't research the problem thoroughly back then. The problem occurs in [`SharedPreferencesProvider#L59`](https://github.com/roboguice/roboguice/blob/master/roboguice/src/main/java/roboguice/inject/SharedPreferencesProvider.java#L59). What seems to go is that `new File("shared_prefs" + ROBOGUICE_1_DEFAULT_FILENAME)` is actually looking for a new file relative to the root, meaning you get a file pointing to a `/shared_prefs` directory, instead of the desired `/data/data/<package>/shared_prefs` directory. This of course in never readable, causing this to always fail.

**Comment by AlexKolpa** [comment]
@stephanenicolas did you have a look at my explanation? If you want, I can also create a quick test to demonstrate the problem of `new File("shared_prefs" + ROBOGUICE_1_DEFAULT_FILENAME).canRead()` always returning false.
