### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by dcgavril** [roboguice/roboguice#311]
From what I can see, there aren't any commits in the past 6 months, and even the pull requests are not treated, so, the question is... will it have any new release in the near future? This is very important, if you want to integrate this library into a new project, because it still uses deprecated code, like ActionBarActivity... and if Google will totally remove support for this type of activity, it will block any kind of sdk updates while using this library.
Thanks!

**Comment by kelsos** [comment]
I am really not sure how this blocks any kind of sdk updates, since you can easily work around the issue inside your project.

Here is the source of [AppCompatActivity](https://android.googlesource.com/platform/frameworks/support/+/master/v7/appcompat/src/android/support/v7/app/AppCompatActivity.java).

You can create your own RoboAppCompatActivity as a base for your activities by copying the code of the original AppCompatActivity and then making it inherit from RoboFragmentActivity or some other basic RoboActivity.

**Comment by dcgavril** [comment]
The point of using a library like this, is to simplify and shorten the time needed to develop an app. By requesting to add or change it's standard behavior, the library loses it's value. Anyway, seeing that in the latest months there weren't any commits and more than a hundred issues reported, I believe I'm stating a fair point when asking if it's still maintained. 
As per the AppCompatActivity - there is already a pull request for that, but nobody to accept it or review it... as with other pull requests. 

I'm not saying that anyone is obligated to deliver updates(most free/open-source libs/tools go through slow phases - I find it normal - it's the same with all my free/side projects), but I'm just trying to understand if there will be any future for this library.
Thanks!

**Comment by emmby** [comment]
Apologies, we're actively working on RoboGuice 4.0 so have been a little
slow with 3.0 maintenance.  Expect some news about 4.0 in the next few
weeks…


On Fri, Jun 26, 2015 at 2:36 AM dcgavril <notifications@github.com> wrote:

> The point of using a library like this, is to simplify and shorten the
> time needed to develop an app. By requesting to add or change it's standard
> behavior, the library loses it's value. Anyway, seeing that in the latest
> months there weren't any commits and more than a hundred issues reported, I
> believe I'm stating a fair point when asking if it's still maintained.
> As per the AppCompatActivity - there is already a pull request for that,
> but nobody to accept it or review it... as with other pull requests.
>
> I'm not saying that anyone is obligated to deliver updates(most
> free/open-source libs/tools go through slow phases - I find it normal -
> it's the same with all my free/side projects), but I'm just trying to
> understand if there will be any future for this library.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roboguice/roboguice/issues/311#issuecomment-115612666>
> .
>
-- 
http://about.me/michaelburton

**Comment by dcgavril** [comment]
No apologies needed, it's great to hear that someone is working on it. Thanks for the update and good luck with the development.
