### ISSUE TITLE
There is something wrong in Button while using roboguice 

### ISSUE THREAD

**Issue by lixuhuang** [roboguice/roboguice#322]
Button backgroud was not showed in some android 2.3 while using roboguice, 
but textview works in the same condition. 
And button background can be show without roboguice inject.
## not works device list 
- ST15i	2.3.3
- Genymotion Google Nexus One 2.3.7
- HTC Z715e

contact me by  email 345136673@qq.com

**Comment by stephanenicolas** [comment]
How can that be related to RoboGuice ?

2015-08-31 0:15 GMT-04:00 lixuhuang <notifications@github.com>:
