### ISSUE TITLE
RoboAsyncTaskLoader and RoboLoader should offer 'provided' versions

### ISSUE THREAD

**Issue by cherrydev** [roboguice/roboguice#334]
While these are trivial to re-implement manually without the dependency on the support library, for completeness I figure it should probably be included.

**Comment by cherrydev** [comment]
*cough* Well considering I just realized that I had written those classes originally that maybe should be me, shouldn't it?

**Comment by stephanenicolas** [comment]
@cherrydev , we are gonna remove all those classes for RG 4. It would be
interesting to have some code somewhere as examples if people want to
inject stuff in loaders and duly take into account their lifecycle, but RG
won't provide those classes anymore.

S.

2016-03-01 16:51 GMT-08:00 cherrydev <notifications@github.com>:
