### ISSUE TITLE
AnnotationDatabaseImpl generated incompletely

### ISSUE THREAD

**Issue by pcockerell** [roboguice/roboguice#338]
Having been using RG 3.0.1 since 2015-08, I've just started to see a problem where  AnnotationDatabaseImpl.java is generated with only a subset of my injections, in particular the ones in the class that I just edited. At runtime, hardly any of the injections are performed and NPEs ensue. The changes I made that might be related are adding a bunch of new dependencies to my build.gradle for unit testing and to get the Nullable that actually works with Guice:

```
    // For @Nullable
    compile 'com.google.code.findbugs:jsr305:2.0.1'

    // This is to resolve a dependency version problem: runner wants 23.0.1, GMS wants this one.
    androidTestCompile 'com.android.support:support-annotations:23.3.0'

    androidTestCompile 'com.android.support.test:runner:0.4.1'
    androidTestCompile 'com.android.support.test:rules:0.4.1'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.1'
    androidTestCompile 'com.android.support.test.uiautomator:uiautomator-v18:2.1.2'

    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:1.10.19'
```

and moving to Android Studio 2.1 beta (just call me Mr Cutting Edge).

I can resolve the problem by doing a clean before the build, but that's not wholly satisfactory.

Any ideas?

**Comment by UNCVR** [comment]
Same problem too, I think it's linked to Android Studio 2 version

**Comment by pcockerell** [comment]
I haven't seen it for a while, with later 2.1 beta releases. I've just upgraded to AS 2.1 final, so if it doesn't recur within a week or so, I'll close this.

**Comment by pcockerell** [comment]
Seems to have been addressed in later AS builds. Closing.
