### ISSUE TITLE
Need to clean to make it work

### ISSUE THREAD

**Issue by mgohin** [roboguice/roboguice#339]
Hi,

I don't know where to check but I have a strange behavior, I need to clean the project everytime I change a piece of java code or I end with an NPE in my App.java because injection isn't working.

Hope we can find what's going on, very annoying :(

**Comment by mgohin** [comment]
I implemented base class to support AppCompatActivity : http://pastebin.com/HqL1BK2M

In `onCreate` the last line is `eventManager.fire(new OnCreateEvent<Activity>(this,savedInstanceState));`. 

Debugging into the fire method : `final Set<EventListener<?>> observers = registrations.get(event.getClass());`. 

When it's working observers = 1, when not observers = null. I tried to go deeper but didn't manage to find the piece of code. 

Looks like listener is missing in `MembersInjectorImpl.java` when calling `encounter.getInjectionListeners()`.

**Comment by ashraful29** [comment]
I have face same problem

**Comment by kelsos** [comment]
Have you tried deactivating the Instant Run option in Android Studio?

**Comment by mgohin** [comment]
It's desactivated ;)

**Comment by flossokay** [comment]
I too am able to reproduce this issue.

**Comment by UNCVR** [comment]
I reproduce this issue too

**Comment by ohin** [comment]
The only way I've got this issue resolved (temporarily) is to downgrade the gradle build tools in main build.gradle file to 2.0.0:

`classpath 'com.android.tools.build:gradle:2.0.0'`

**Comment by DTHENG** [comment]
@ohin thanks! That worked for me!

**Comment by Skyd1400** [comment]
Same problem, same workaround. But it's a shame 'cause Instant run is so cool. I've flashed my phone to lollipop just for it...

**Comment by liraz** [comment]
I suspect that Instant Run is checking changes statically, while RoboGuice is injecting through reflection - so the process of Instant Run thinks the injections are not really being used, so things are being omitted..
But that's just an assumption.

Version 2.1.2 is out, and the problem still persists - i can't use the huge benefits of Instant Run because i chose RoboGuice for my project.
