### ISSUE TITLE
Roboblender with kotlin

### ISSUE THREAD

**Issue by kelsos** [roboguice/roboguice#340]
I am attempting to use Roboblender (4.0.0) with a project I just converted to kotlin and I encountered a strange issue.  

I am not sure if this is a design choice or a bug, but it seems that the kotlin annotation processor (kapt) passes all the detected annotations to the process method of the annotation processor and not only the supported annotations. I managed to confirm that this is also the case with DBFlow's processor.

In my case this caused a problem since blender tried to process a method that had a retrofit annotation and a primitive parameter (Blender failed with a type cast error). 

The good news is that if you ignore the unsupported annotations in the process method everything seems to work fine.

``` java
            String annotationClassName = getTypeName(annotation);

            if (!getSupportedAnnotationTypes().contains(annotationClassName)) {
                continue;
            }

            //merge the 2 inject annotations
            if( "javax.inject.Inject".equals(annotationClassName) ) {
                annotationClassName = "com.google.inject.Inject";
            }



```

**Comment by bvic23** [comment]
Hi,

I have the same problem. Are you aware of some workaround? Shall I rebuild roboblender?

**Comment by kelsos** [comment]
I had to rebuild roboblender with the following lines mentioned above and use a local snapshot.

**Comment by bvic23** [comment]
Hi Konstantinos,

Thank you for your quick answer!

Bests,v
