### ISSUE TITLE
Injection does not work with Instant Run

### ISSUE THREAD

**Issue by UNCVR** [roboguice/roboguice#345]
Since gradle 2.1.0 release, Roboguice doesn't work correctly.

Using Instant Run, I got NPE for injected class.

When I deactivate Instant Run, I need to clean before each build otherwise app crashes for obscur reasons.

Only way to make it works is to downgrade to gradle 2.0.0 and not use Instant Run.

Is this library still maintained ? I use it since almost 2 years and it used to work absolutely well but since last gradle release, it become hard to code with and the lack of support for last issues makes it hard to trust for future development...

**Comment by stephanenicolas** [comment]
@UNCVR RG release 4.0.0 is gonna be our final release. We didn't announce
it yet as we have had some production issues (not related to RG) that
prevented us from benchmarking it accurately in production.

After that, we will announce the latest release (which breaks quite a few
things actually).. and this will be the final release of RG.

We are currently putting all our development efforts in a new DI library,
as easy to use as RG but as fast as dagger 1 & 2:
https://github.com/stephanenicolas/toothpick

S.

2016-07-09 6:50 GMT-07:00 UNCVR <notifications@github.com>:

**Comment by MrLepage** [comment]
I have just seen the README update of Mike. I suppose you gave up to release version 4.0.0 ?

Is toothpick actively developed and do you think final release 1.0.0 will come soon ? I have read the wiki but for Android I found it hard to use for now..

Many thanx for your work

A.
